name: expense_tracker
description: "Expense Tracker - Clean Architecture Demo"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.11.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  app:
    path: packages/app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  ignorium: ^1.0.0

flutter:
  uses-material-design: true
