name: core_chain
description: Pipeline for data transformation and validation
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  core_result:
    path: ../core_result

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
