name: app
description: Main application entry point
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.1 <4.0.0"

resolution: workspace

dependencies:
  core_bloc:
    path: ../core_bloc
  core_event_bus:
    path: ../core_event_bus
  core_expense_domain:
    path: ../core_expense_domain
  core_l10n:
    path: ../core_l10n
  core_navigation:
    path: ../core_navigation
  core_platform:
    path: ../core_platform
  feature_chart:
    path: ../feature_chart
  feature_expense_detail:
    path: ../feature_expense_detail
  feature_expenses_list:
    path: ../feature_expenses_list
  feature_home:
    path: ../feature_home
  feature_transaction_form:
    path: ../feature_transaction_form
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: "8.0.3"
  shared_preferences: "2.3.5"

dev_dependencies:
  flutter_lints: "6.0.0"
  flutter_test:
    sdk: flutter
