name: app
description: Main application entry point
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.1 <4.0.0"

resolution: workspace

dependencies:
  core_bloc:
    path: ../core_bloc
  core_l10n:
    path: ../core_l10n
  core_navigation:
    path: ../core_navigation
  feature_expenses:
    path: ../feature_expenses
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: "8.0.3"
  shared_preferences: "2.3.5"

dev_dependencies:
  flutter_lints: "6.0.0"
  flutter_test:
    sdk: flutter
