name: feature_expenses
description: Expense tracker feature package
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.1 <4.0.0"

resolution: workspace

dependencies:
  core_bloc:
    path: ../core_bloc
  core_failure:
    path: ../core_failure
  core_l10n:
    path: ../core_l10n
  core_navigation:
    path: ../core_navigation
  core_result:
    path: ../core_result
  flutter:
    sdk: flutter
  flutter_bloc: "9.1.1"
  freezed_annotation: "3.1.0"
  get_it: "8.0.3"
  json_annotation: "4.11.0"
  shared_preferences: "2.3.5"
  uuid: "4.5.1"

dev_dependencies:
  build_runner: "2.14.1"
  flutter_lints: "6.0.0"
  flutter_test:
    sdk: flutter
  freezed: "3.2.5"
  json_serializable: "6.13.1"
  mocktail: "1.0.4"
