name: core_bloc
description: Base BLoC class for state management
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.11.1 <4.0.0"

resolution: workspace

dependencies:
  bloc: "9.0.0"

dev_dependencies:
  lints: "6.0.0"
